
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws/", className = "proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws/", className = "proxy.ConvertResponse")
    @Action(input = "http://ws/BanqueService/ConvertRequest", output = "http://ws/BanqueService/ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listcomptes", targetNamespace = "http://ws/", className = "proxy.Listcomptes")
    @ResponseWrapper(localName = "listcomptesResponse", targetNamespace = "http://ws/", className = "proxy.ListcomptesResponse")
    @Action(input = "http://ws/BanqueService/listcomptesRequest", output = "http://ws/BanqueService/listcomptesResponse")
    public List<Compte> listcomptes();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://ws/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://ws/", className = "proxy.GetcompteResponse")
    @Action(input = "http://ws/BanqueService/getcompteRequest", output = "http://ws/BanqueService/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
